server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test001?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lol.po

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
